### ISSUE TITLE
AttributeError: 'module' object has no attribute 'io'

### ISSUE THREAD

**Issue by mathematiguy** [reiinakano/neural-painters#19]
Thanks for sharing this awesome project `reiinakano` - I've been working on running your notebooks locally on my own machine inside a docker container.

When running the notebook `learning_human_strokes.ipynb` I get the following error when running the code `mnist_dispenser = MNISTDispenser()`:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-cf17af3d2e33> in <module>()
----> 1 mnist_dispenser = MNISTDispenser()

<ipython-input-5-da69b5df8a4d> in __init__(self, data_dir, screen_size)
      4         self.data_dir = data_dir
      5         self.height, self.width = screen_size, screen_size
----> 6         self.prepare_mnist()
      7 
      8     def get_random_target(self, num=1, squeeze=False):

<ipython-input-5-da69b5df8a4d> in prepare_mnist(self)
     14 
     15     def prepare_mnist(self):
---> 16         ut.io.makedirs(self.data_dir)
     17 
     18         # ground truth MNIST data

AttributeError: 'module' object has no attribute 'io'
``` 

Looking at the code, it looks like the line `import utils as ut` imports  [utils.py](https://github.com/reiinakano/SPIRAL-tensorflow/blob/reiinakano-patch-2/envs/utils.py) from the [SPIRAL-tensorflow](https://github.com/reiinakano/SPIRAL-tensorflow) repo. `utils.py` doesn't define an `io` attribute, which is why the code breaks.

I checked the git history of the file in case it used to have an `io` method but no longer does, and didn't manage to find anything.

Is this correct? I'm not sure what the `ut.io` module is supposed to do, so I'm nervous about overwriting a hack onto it.

**Comment by reiinakano** [comment]
`utils` actually refers to the `utils` *module* (the folder). In that folder, there is an `io.py` which is what is being imported as `ut.io.makedirs`.
